export const SITE_CONFIG = {
  name: 'Toz Yapı Teknolojileri',
  tagline: 'Yapı Teknolojilerinde 18 Yıllık Uzmanlık',
  description: 'Ankara merkezli yapı teknolojileri firması. Alüminyum doğrama, otomatik kapılar, pergola, kepenk, panjur, akıllı cam ve 50+ ürün kategorisinde 18 yıllık deneyim.',
  url: 'https://www.tozyapi.com.tr',
  phone: '+90 536 773 14 04',
  phoneFormatted: '0536 773 14 04',
  whatsapp: '905367731404',
  email: 'merhaba@tozyapi.com.tr',
  emailLuna: 'Luna@tozyapi.com.tr',
  address: 'Timko İş Merkezi, Çamlıca Mah. Anadolu Bulvarı İdil Sk. Ğ Blok No:20 V-8',
  addressFull: 'Timko İş Merkezi, Çamlıca Mahallesi Anadolu Bulvarı İdil Sokak Ğ Blok No:20 V-8, 06200 Yenimahalle / Ankara',
  addressShort: 'Yenimahalle / Ankara',
  instagram: '@toz.solutions',
  instagramUrl: 'https://www.instagram.com/toz.solutions',
  mapUrl: 'https://maps.google.com/?q=Timko+İş+Merkezi+Yenimahalle+Ankara',
  workingHours: [
    { days: 'Pazartesi – Cuma', hours: '09:00 – 17:00', open: true },
    { days: 'Cumartesi', hours: 'Kapalı', open: false },
    { days: 'Pazar', hours: 'Kapalı', open: false },
  ],
}

export const WHATSAPP_URL = (message = 'Merhaba! Bilgi almak istiyorum.') =>
  `https://wa.me/${SITE_CONFIG.whatsapp}?text=${encodeURIComponent(message)}`

export const STATS = [
  { value: '18', suffix: '+', label: 'Yıl Deneyim' },
  { value: '500', suffix: '+', label: 'Tamamlanan Proje' },
  { value: '984', suffix: '+', label: 'Mutlu Müşteri' },
  { value: '50', suffix: '+', label: 'Ürün Kategorisi' },
]

export const PRODUCT_CATEGORIES = [
  {
    id: 'dograma-cephe',
    title: 'Doğrama & Cephe Çözümleri',
    shortTitle: 'Doğrama & Cephe',
    slug: 'dograma-cephe',
    icon: '🏗️',
    description: '6063T6 alüminyum termal kırılımlı profiller, PVC ve ahşap kapı, pencere, cephe sistemleri',
    specs: ['6063T6 Termal Kırılımlı Alüminyum', 'UW 0.9 W/m²K Yalıtım', 'CE Sertifikalı Profil', '%25 Enerji Tasarrufu'],
    subcategories: [
      { title: 'Ahşap Kapı, Pencere ve Doğrama', slug: 'ahsap-dograma' },
      { title: 'Alüminyum Kapı, Pencere ve Doğrama', slug: 'aluminyum-dograma', highlight: true },
      { title: 'PVC Kapı, Pencere ve Doğrama', slug: 'pvc-dograma' },
    ],
    downloads: {
      katalog: true, bim: true, cad: true, ifc: true, sertifika: true,
    },
  },
  {
    id: 'kapi-sistemleri',
    title: 'Kapı Sistemleri',
    shortTitle: 'Kapı Sistemleri',
    slug: 'kapi-sistemleri',
    icon: '🚪',
    description: 'Garaj, otomatik, akustik, hermetik, yangın ve endüstriyel kapı sistemleri',
    specs: ['Fotoselli Sensör Sistemi', 'Seksiyonel & Full Vision', 'Hermetik Kapılar', 'Endüstriyel Sınıf'],
    subcategories: [
      { title: 'Garaj Kapıları', slug: 'garaj-kapilari', highlight: true },
      { title: 'Otomatik Kapılar', slug: 'otomatik-kapilar', highlight: true },
      { title: 'Akustik Kapılar', slug: 'akustik-kapilar' },
      { title: 'Hermetik Kapılar', slug: 'hermetik-kapilar' },
      { title: 'Bahçe Kapıları', slug: 'bahce-kapilari' },
      { title: 'Yangın Kapıları', slug: 'yangin-kapilari' },
      { title: 'PVC Hızlı Kapılar', slug: 'pvc-kapilari' },
    ],
    downloads: {
      katalog: true, bim: true, cad: true, ifc: false, sertifika: true,
    },
  },
  {
    id: 'kepenk-sistemleri',
    title: 'Kepenk Sistemleri',
    shortTitle: 'Kepenk',
    slug: 'kepenk-sistemleri',
    icon: '🔒',
    description: 'Alüminyum, çelik, balistik koruma, şeffaf ve motorlu kepenk çözümleri',
    specs: ['Balistik Koruma Sınıfı', 'Motorlu Sistem', 'Uzaktan Kumanda', 'Poliüretan Dolgulu Seçenek'],
    subcategories: [
      { title: 'Alüminyum Kepenk', slug: 'aluminyum-kepenk' },
      { title: 'Alüminyum Poliüretan Dolgulu', slug: 'polyuretan-kepenk', highlight: true },
      { title: 'Balistik Kepenk', slug: 'balistik-kepenk', highlight: true },
      { title: 'Katlanır Kepenk', slug: 'katlanir-kepenk' },
      { title: 'Kayar Katlanır Kepenk', slug: 'kayar-katlanir-kepenk' },
      { title: 'Çelik (Sac) Kepenk', slug: 'celik-kepenk' },
      { title: 'Çelik Poliüretan Dolgulu', slug: 'celik-polyuretan' },
      { title: 'Şeffaf Kepenk', slug: 'seffaf-kepenk' },
    ],
    downloads: {
      katalog: true, bim: false, cad: true, ifc: false, sertifika: true,
    },
  },
  {
    id: 'panjur-sistemleri',
    title: 'Panjur Sistemleri',
    shortTitle: 'Panjur',
    slug: 'panjur-sistemleri',
    icon: '🪟',
    description: 'Monoblok, gizli, ahşap ve motorlu panjur sistemleri ile ısı ve ses kontrolü',
    specs: ['Gizli / Monoblok Kutu', 'Motorlu Çalışma', 'Isı Yalıtım Katkısı', 'Akıllı Ev Uyumlu'],
    subcategories: [
      { title: 'Monoblok Panjur', slug: 'monoblok-panjur', highlight: true },
      { title: 'Gizli Panjur', slug: 'gizli-panjur' },
      { title: 'Dıştan Takma Panjur', slug: 'distar-panjur' },
      { title: 'Ahşap Panjur', slug: 'ahsap-panjur' },
      { title: 'Kayar Katlanır Panjur', slug: 'kayar-panjur' },
      { title: 'Makaslı Panjur', slug: 'makasli-panjur' },
      { title: 'Menteşeli Panjur', slug: 'menteseli-panjur' },
      { title: 'Strafor Kutu / Lento Kutu', slug: 'lento-kutu' },
    ],
    downloads: {
      katalog: true, bim: true, cad: true, ifc: true, sertifika: false,
    },
  },
  {
    id: 'pergola-tente',
    title: 'Pergola, Rolling Roof & Tente',
    shortTitle: 'Pergola & Tente',
    slug: 'pergola-tente',
    icon: '⛺',
    description: 'Bioclimatic, rolling roof, cam tavan ve tente sistemleriyle dört mevsim dış mekan konforu',
    specs: ['Motorlu Kanat Sistemi', 'Yağmur Sensörü', 'LED Aydınlatma', 'Rüzgar Dayanımı'],
    subcategories: [
      { title: 'Bioclimatic Pergola', slug: 'bioclimatic', highlight: true },
      { title: 'Rolling Roof', slug: 'rolling-roof', highlight: true },
      { title: 'Cam Tavan', slug: 'cam-tavan' },
      { title: 'Klasik Pergola', slug: 'pergola' },
      { title: 'Tente Sistemleri', slug: 'tente' },
    ],
    downloads: {
      katalog: true, bim: false, cad: true, ifc: false, sertifika: false,
    },
  },
  {
    id: 'zip-perde',
    title: 'Zip Perde, Giyotin & Rüzgar Kırıcı',
    shortTitle: 'Zip Perde & Giyotin',
    slug: 'zip-perde',
    icon: '💨',
    description: 'Zip perde, giyotin cam, rüzgar kırıcı ve sürme sistemleriyle açık alanları dört mevsim kullanın',
    specs: ['Zip Kilitleme Sistemi', 'Rüzgar Koruması', 'Şeffaf Görünüm', 'Motorlu veya Manuel'],
    subcategories: [
      { title: 'Zip Perde Sistemleri', slug: 'zip-perde-sistem', highlight: true },
      { title: 'Giyotin Sistemleri', slug: 'giyotin', highlight: true },
      { title: 'Rüzgar Kırıcı', slug: 'ruzgar-kirici' },
      { title: 'Sürme Sistemleri', slug: 'surme-sistemleri' },
    ],
    downloads: {
      katalog: true, bim: false, cad: true, ifc: false, sertifika: false,
    },
  },
  {
    id: 'akilli-cam',
    title: 'Akıllı Cam Uygulamaları',
    shortTitle: 'Akıllı Cam',
    slug: 'akilli-cam',
    icon: '✨',
    description: 'Elektrokromik cam teknolojisiyle anında gizlilik kontrolü ve enerji verimliliği',
    specs: ['Anında Opaklık Kontrolü', 'UV Koruması', 'Enerji Tasarrufu', 'Smart Home Uyumlu'],
    subcategories: [
      { title: 'Elektrokromik Cam', slug: 'elektrokromik-cam', highlight: true },
      { title: 'Gizlilik Kontrollü Cam', slug: 'gizlilik-cam' },
      { title: 'Isı Kontrol Camlı Sistemler', slug: 'isi-cam' },
    ],
    downloads: {
      katalog: true, bim: false, cad: false, ifc: false, sertifika: true,
    },
  },
  {
    id: 'kis-bahcesi',
    title: 'Kış Bahçesi',
    shortTitle: 'Kış Bahçesi',
    slug: 'kis-bahcesi',
    icon: '🌿',
    description: 'Dört mevsim yaşam alanı sunan ısı yalıtımlı alüminyum kış bahçesi sistemleri',
    specs: ['4 Mevsim Konfor', 'Isı Yalıtımlı Çerçeve', 'Çift Cam Sistemi', 'Mimari Entegrasyon'],
    subcategories: [
      { title: 'Alüminyum Kış Bahçesi', slug: 'aluminyum-kis-bahcesi', highlight: true },
      { title: 'Cam Kış Bahçesi', slug: 'cam-kis-bahcesi' },
      { title: 'Isıtmalı Kış Bahçesi', slug: 'isitmali-kis-bahcesi' },
    ],
    downloads: {
      katalog: true, bim: true, cad: true, ifc: false, sertifika: false,
    },
  },
  {
    id: 'dis-cephe-jaluzi',
    title: 'Dış Cephe Jaluzisi – Brisoley',
    shortTitle: 'Brisoley',
    slug: 'dis-cephe-jaluzi',
    icon: '🏢',
    description: 'Güneş kırıcı brise soleil sistemleriyle enerji tasarrufu ve mimari estetik',
    specs: ['Güneş Açısı Kontrolü', 'Enerji Tasarrufu', 'Mimari Entegrasyon', 'Motorlu Kontrol'],
    subcategories: [
      { title: 'Yatay Brisoley', slug: 'yatay-brisoley', highlight: true },
      { title: 'Dikey Brisoley', slug: 'dikey-brisoley' },
      { title: 'Motorlu Jaluzi', slug: 'motorlu-jaluzi' },
    ],
    downloads: {
      katalog: true, bim: true, cad: true, ifc: true, sertifika: true,
    },
  },
  {
    id: 'turnike-bariyer',
    title: 'Turnike & Bariyer Sistemleri',
    shortTitle: 'Turnike & Bariyer',
    slug: 'turnike-bariyer',
    icon: '🚧',
    description: 'Güvenli giriş-çıkış kontrolü için turnike, bariyer ve araç tanıma sistemleri',
    specs: ['RFID / Kart Entegrasyon', 'Araç Tanıma Sistemi', '24/7 Çalışma', 'Güvenlik Protokolü'],
    subcategories: [
      { title: 'Bariyer Sistemleri', slug: 'bariyer', highlight: true },
      { title: 'Turnike Sistemleri', slug: 'turnike' },
    ],
    downloads: {
      katalog: true, bim: false, cad: true, ifc: false, sertifika: true,
    },
  },
  {
    id: 'sundurma-carport',
    title: 'Sundurma & Araç Parkı (Carport)',
    shortTitle: 'Carport & Sundurma',
    slug: 'sundurma-carport',
    icon: '🚗',
    description: 'Güçlü statik hesaplı alüminyum carport ve sundurma sistemleri',
    specs: ['Güçlü Statik Hesap', 'Yağmur & Kar Dayanımı', 'Solar Panel Uyumlu', 'Modüler Yapı'],
    subcategories: [
      { title: 'Carport Sistemleri', slug: 'carport', highlight: true },
      { title: 'Sundurma', slug: 'sundurma' },
      { title: 'Solar Carport', slug: 'solar-carport' },
    ],
    downloads: {
      katalog: true, bim: false, cad: true, ifc: false, sertifika: false,
    },
  },
  {
    id: 'havuz-kapama',
    title: 'Havuz Kapama Çözümleri',
    shortTitle: 'Havuz Kapama',
    slug: 'havuz-kapama',
    icon: '🏊',
    description: 'Villa ve otel havuzları için güvenlik onaylı otomatik kapama sistemleri',
    specs: ['Güvenlik Sertifikalı', 'Motorlu Sistem', 'UV Dayanımlı', 'Çocuk Kilidi'],
    subcategories: [
      { title: 'Otomatik Havuz Kapağı', slug: 'otomatik-havuz-kapagi', highlight: true },
      { title: 'Cam Havuz Kapağı', slug: 'cam-havuz-kapagi' },
    ],
    downloads: {
      katalog: true, bim: false, cad: false, ifc: false, sertifika: true,
    },
  },
  {
    id: 'sineklik',
    title: 'Sineklik Sistemleri',
    shortTitle: 'Sineklik',
    slug: 'sineklik',
    icon: '🔧',
    description: 'Yerli ve ithal pliseli, rulo ve kanatlı sineklik çözümleri',
    specs: ['Paslanmaz Çelik Çerçeve', 'Kolay Montaj', 'Fibre Cam File', 'Her Pencere Uyumlu'],
    subcategories: [
      { title: 'Pliseli Sineklik', slug: 'pliseli-sineklik', highlight: true },
      { title: 'Rulo Sineklik', slug: 'rulo-sineklik' },
      { title: 'Kanatlı Sineklik', slug: 'kanatli-sineklik' },
    ],
    downloads: {
      katalog: true, bim: false, cad: false, ifc: false, sertifika: false,
    },
  },
  {
    id: 'bahce-cit',
    title: 'Bahçe & Çit Sistemleri',
    shortTitle: 'Bahçe & Çit',
    slug: 'bahce-cit',
    icon: '🌳',
    description: 'Galvanizli çelik ve alüminyum panel çit, bahçe kapısı ve çevre düzenleme sistemleri',
    specs: ['Galvanizli Çelik', 'Toz Boyalı', 'Uzun Ömür', 'Güvenlik Odaklı'],
    subcategories: [
      { title: 'Panel Çit', slug: 'panel-cit', highlight: true },
      { title: 'Alüminyum Çit', slug: 'aluminyum-cit' },
      { title: 'Bahçe Kapısı', slug: 'bahce-kapisi' },
    ],
    downloads: {
      katalog: true, bim: false, cad: true, ifc: false, sertifika: false,
    },
  },
  {
    id: 'isitma-sogutma',
    title: 'Isıtma & Soğutma Sistemleri',
    shortTitle: 'HVAC',
    slug: 'isitma-sogutma',
    icon: '❄️',
    description: 'VRF, chiller ve fan coil sistemleriyle enerji tasarruflu klimatizasyon çözümleri',
    specs: ['A+++ Enerji Sınıfı', 'BMS Entegrasyon', 'Sessiz Çalışma', 'Uzaktan Kontrol'],
    subcategories: [
      { title: 'VRF Sistemler', slug: 'vrf', highlight: true },
      { title: 'Chiller Sistemler', slug: 'chiller' },
      { title: 'Fan Coil Üniteleri', slug: 'fan-coil' },
    ],
    downloads: {
      katalog: true, bim: false, cad: false, ifc: false, sertifika: true,
    },
  },
  {
    id: 'acik-hava-mutfagi',
    title: 'Açık Hava Mutfakları',
    shortTitle: 'Dış Mutfak',
    slug: 'acik-hava-mutfagi',
    icon: '🍽️',
    description: 'Paslanmaz çelik 316L ile üretilmiş, hava koşullarına dayanıklı dış mekan mutfak sistemleri',
    specs: ['Paslanmaz Çelik 316L', 'Hava Koşullarına Dayanıklı', 'Modüler Tasarım', 'Premium Estetik'],
    subcategories: [
      { title: 'Modüler Dış Mutfak', slug: 'moduler-mutfak', highlight: true },
      { title: 'BBQ & Grill Adaları', slug: 'bbq-adasi' },
    ],
    downloads: {
      katalog: true, bim: false, cad: false, ifc: false, sertifika: false,
    },
  },
]

export const BLOG_POSTS = [
  {
    id: 1,
    title: 'Alüminyum Doğrama Seçiminde 10 Kritik Teknik Kriter',
    slug: 'aluminyum-dograma-secim-kriterleri',
    category: 'Teknik Rehber',
    excerpt: '6063T6 profil alaşımından termal kırılım genişliğine, cam paketi seçiminden menteşe kalitesine — doğru alüminyum doğramayı seçmek için bilmeniz gereken her şey.',
    date: '2026-03-18',
    readTime: '8 dk',
    tags: ['alüminyum', 'doğrama', 'enerji', 'teknik'],
    relatedProducts: ['dograma-cephe'],
  },
  {
    id: 2,
    title: 'Bioclimatic Pergola ile Rolling Roof: Hangisi Size Göre?',
    slug: 'bioclimatic-pergola-vs-rolling-roof',
    category: 'Ürün Karşılaştırma',
    excerpt: 'Motorlu kanat sistemi mi, yoksa katlanır çatı mı? İki sistemin rüzgar dayanımı, maliyet ve kullanım senaryosu karşılaştırması.',
    date: '2026-03-12',
    readTime: '6 dk',
    tags: ['pergola', 'bioclimatic', 'rolling roof', 'dış mekan'],
    relatedProducts: ['pergola-tente'],
  },
  {
    id: 3,
    title: 'Hastanelerde Hermetik Kapı: Enfeksiyon Kontrolünde Teknik Standartlar',
    slug: 'hastane-hermetik-kapi-standartlari',
    category: 'Sektörel Uygulama',
    excerpt: 'Ameliyathane, yoğun bakım ve steril alanlar için hermetik kapı seçiminde dikkat edilmesi gereken teknik normlar ve sertifika gereksinimleri.',
    date: '2026-03-05',
    readTime: '7 dk',
    tags: ['hermetik kapı', 'hastane', 'steril', 'sağlık'],
    relatedProducts: ['kapi-sistemleri'],
  },
  {
    id: 4,
    title: 'Zip Perde ve Giyotin Cam: Açık Alanı Dört Mevsim Kullanın',
    slug: 'zip-perde-giyotin-cam-farki',
    category: 'Uygulama Rehberi',
    excerpt: 'Balkon, teras ve restoran gibi açık alanların kışın korunması için zip perde ve giyotin cam sistemleri arasındaki farklar ve seçim kriterleri.',
    date: '2026-02-25',
    readTime: '5 dk',
    tags: ['zip perde', 'giyotin', 'teras', 'kış kullanımı'],
    relatedProducts: ['zip-perde'],
  },
  {
    id: 5,
    title: 'Balistik Kepenk: Güvenlik Sınıfları ve Sertifikasyon Süreci',
    slug: 'balistik-kepenk-guvenlik-siniflari',
    category: 'Güvenlik',
    excerpt: 'BR2–BR6 güvenlik sınıfları arasındaki farklar, balistik kepengin kullanım alanları ve uluslararası sertifika gereksinimleri.',
    date: '2026-02-18',
    readTime: '6 dk',
    tags: ['balistik', 'güvenlik', 'kepenk', 'sertifika'],
    relatedProducts: ['kepenk-sistemleri'],
  },
  {
    id: 6,
    title: 'Dış Cephe Jaluzisinde Enerji Verimliliği: Güneş Açısı Hesaplama',
    slug: 'dis-cephe-jaluzi-enerji-verimliligi',
    category: 'Enerji & Tasarruf',
    excerpt: 'Brise soleil sistemlerinin doğru konumlandırılmasıyla yıllık ısıtma-soğutma maliyetlerini %30\'a kadar düşürmenin teknik yöntemi.',
    date: '2026-02-10',
    readTime: '5 dk',
    tags: ['brisoley', 'enerji', 'güneş', 'tasarruf'],
    relatedProducts: ['dis-cephe-jaluzi'],
  },
  {
    id: 7,
    title: 'BIM, CAD ve IFC Dosyalarının İnşaat Projelerindeki Önemi',
    slug: 'bim-cad-ifc-inşaat-projeleri',
    category: 'Teknik Dokümantasyon',
    excerpt: 'Mimarlar ve mühendisler için BIM entegrasyonu neden kritik? Revit, IFC ve DWG formatlarının projeye katkısı ve nasıl talep edileceği.',
    date: '2026-02-03',
    readTime: '6 dk',
    tags: ['BIM', 'CAD', 'IFC', 'mühendislik'],
    relatedProducts: [],
  },
  {
    id: 8,
    title: 'Kış Bahçesi Tasarımında Cam ve Profil Seçimi',
    slug: 'kis-bahcesi-cam-profil-secimi',
    category: 'Tasarım Rehberi',
    excerpt: 'Yıl boyu konforlu kış bahçesi için çift/üçlü cam seçenekleri, alüminyum profil sistemi ve ısı yalıtım değerlerinin karşılaştırması.',
    date: '2026-01-27',
    readTime: '7 dk',
    tags: ['kış bahçesi', 'cam', 'profil', 'yalıtım'],
    relatedProducts: ['kis-bahcesi'],
  },
]

export const PARTNERS = [
  { name: 'Schüco' },
  { name: 'Roto' },
  { name: 'Winkhaus' },
  { name: 'FAAC' },
  { name: 'Nice' },
  { name: 'Hörmann' },
  { name: 'Rehau' },
  { name: 'Veka' },
  { name: 'Deceuninck' },
  { name: 'Gealan' },
  { name: 'Sommer' },
  { name: 'Aluk' },
]

export const REFERENCE_SECTORS = [
  { label: 'Otel & Konaklama',   icon: '🏨', count: 5,     highlight: false },
  { label: 'Sağlık & Hastane',   icon: '🏥', count: 14,    highlight: true  },
  { label: 'AVM & Ticari',       icon: '🏬', count: 6,     highlight: false },
  { label: 'Kamu & Kurumsal',    icon: '🏛️', count: 83,   highlight: true  },
  { label: 'Endüstriyel Tesis',  icon: '🏭', count: 55,    highlight: false },
  { label: 'Konut & Rezidans',   icon: '🏠', count: '100+',highlight: false },
]

export const REFERENCES = [
  {
    name: 'Ankara Şehir Hastanesi',
    type: 'Sağlık & Hastane',
    products: 'Hermetik kapılar, steril zon doğramaları, otomatik kapı sistemleri',
    city: 'Ankara',
  },
  {
    name: 'Hacettepe Üniversitesi Hastanesi',
    type: 'Sağlık & Hastane',
    products: 'Alüminyum doğrama, panjur sistemleri, fotoselli kapılar',
    city: 'Ankara',
  },
  {
    name: 'Gazi Üniversitesi Diş Hekimliği Fakültesi',
    type: 'Kamu & Kurumsal',
    products: 'Alüminyum cephe doğraması, PVC pencereler',
    city: 'Ankara',
  },
  {
    name: 'Bilkent Center AVM',
    type: 'AVM & Ticari',
    products: 'Otomatik kapılar, kepenk sistemleri, bariyer sistemi',
    city: 'Ankara',
  },
  {
    name: 'Ankara Büyükşehir Belediyesi — İdari Binalar',
    type: 'Kamu & Kurumsal',
    products: 'Turnike, bariyer, cephe doğraması, panjur',
    city: 'Ankara',
  },
  {
    name: 'TBMM — Hizmet Binaları',
    type: 'Kamu & Kurumsal',
    products: 'Alüminyum doğrama, güvenlikli giriş kapıları',
    city: 'Ankara',
  },
  {
    name: 'Hilton Garden Inn Ankara',
    type: 'Otel & Konaklama',
    products: 'Bioclimatic pergola, kış bahçesi, alüminyum doğrama',
    city: 'Ankara',
  },
  {
    name: 'Ankara OSB — Endüstriyel Tesisler',
    type: 'Endüstriyel Tesis',
    products: 'Endüstriyel seksiyonel garaj kapıları, hızlı kapılar, kepenk',
    city: 'Ankara',
  },
  {
    name: 'TOKİ Konut Projeleri',
    type: 'Konut & Rezidans',
    products: 'PVC pencere, monoblok panjur, alüminyum balkon doğraması',
    city: 'Türkiye Geneli',
  },
  {
    name: 'Kızılcahamam Belediyesi',
    type: 'Kamu & Kurumsal',
    products: 'Cephe doğraması, kepenk sistemleri, otomatik kapılar',
    city: 'Ankara',
  },
]

export const FAQ = [
  {
    q: 'Alüminyum ve PVC doğrama arasındaki farklar nelerdir?',
    a: '6063T6 termal kırılımlı alüminyum profiller daha uzun ömürlü, şekil almaz ve büyük açıklıklara uygundur. PVC genellikle daha ekonomik ve iyi ısı yalıtım sunar. Termal kırılımlı alüminyum her iki avantajı birden sağlar; UW değeri 0.9 W/m²K\'e kadar inerek PVC ile rekabet eder.',
  },
  {
    q: 'Bioclimatic pergola ile rolling roof farkı nedir?',
    a: 'Bioclimatic pergola, motorlu dönebilen alüminyum kanatlarla havalandırma ve yağmur koruması sunar; kanatlar 0°–135° arasında ayarlanır. Rolling Roof ise zip sistemiyle tamamen açılıp kapanan su geçirmez bir çatıdır. İki sistem farklı kullanım senaryolarına hitap eder.',
  },
  {
    q: 'Hastane için hangi kapı sistemi önerilir?',
    a: 'Steril ortamlar için paslanmaz veya HPL kaplı hermetik kapılar standart gerekliliktir. Ameliyathaneler için EN 13637 normu, yoğun bakım için ise EN 1125 tahliye donanımı şartı aranır. Tüm sağlık projelerimizde teknik şartnameye uygun belgelendirme sağlıyoruz.',
  },
  {
    q: 'Montaj süreci nasıl işler, ne kadar sürer?',
    a: 'Keşif ve teknik ölçüm → Üretim (ürüne göre 2–6 hafta) → Profesyonel montaj ekibiyle kurulum. Tekil ürünler 1–3 iş günü içinde monte edilir. Büyük cephe projeleri proje büyüklüğüne bağlı olarak 2–8 hafta sürebilir.',
  },
  {
    q: 'Garanti kapsamı ve süresi nedir?',
    a: 'Paslanmaz çelik menteşeler için 20 yıl, yapısal profil ve bileşenler için 10 yıl, motor ve mekanik aksam için 5 yıl garanti sunmaktayız. Tüm ürünler CE belgeli olup Avrupa mühendislik standartlarına uygundur.',
  },
  {
    q: 'BIM, CAD ve IFC dosyaları temin edilebilir mi?',
    a: 'Evet. Revit (.rfa), IFC, DWG ve STEP formatlarında teknik çizimler ve BIM dosyaları talep üzerine ücretsiz sağlanmaktadır. BIM Kütüphanesi sayfamızdan doğrudan indirebilir ya da projelerinize özel format için bize ulaşabilirsiniz.',
  },
  {
    q: 'Ankara dışında hizmet veriyor musunuz?',
    a: 'Evet, tüm Türkiye\'ye teknik hizmet ve montaj sağlıyoruz. Ankara ve çevresi için 24–48 saat içinde keşif ekibimiz yerinde olur. İl dışı projeler için bölge koordinasyonu yaparak aynı kalite standartlarını uyguluyoruz.',
  },
  {
    q: 'Akıllı ev / bina otomasyonu entegrasyonu mümkün mü?',
    a: 'Motorlu panjur, kepenk, pergola, zip perde ve kapı sistemlerimizin büyük çoğunluğu KNX, Z-Wave, Zigbee ve yaygın akıllı ev platformlarıyla entegre edilebilir. Proje bazlı otomasyon çözümü için teknik ekibimizle görüşmenizi öneririz.',
  },
]
